a=int(input('enter the value of a:'))
b=int(input('enter the value of b:'))
print('hear the value of a:',a)
print('hear the value of b:',b)
print('hear the total:',a+b)
#-------------multiplication----
print('multiplication')
a=int(input('enter the value of a:'))
b=int(input('enter the value of b:'))
print('hear the value of a:',a)
print('hear the value of b:',b)
print('hear the total:',a*b)
#---------------(-)-------
print('minas')
a=int(input('enter the value of a:'))
b=int(input('enter the value of b:'))
print('hear the value of a:',a)
print('hear the value of b:',b)
print('hear the total:',a-b)
#--------division-----------
a=int(input('enter the value of a:'))
b=int(input('enter the value of b:'))
print('hear the value of a:',a)
print('hear the value of b:',b)
print('hear the total:',a/b)